version: "3.7"
services:
  userservice:
    image: asbjorndev/auction-userservice-image:1.0.0
    environment:
      - ConnectionURI=mongodb+srv://admin:admin@auctionhouse.dfo2bcd.mongodb.net/
    ports:
      - "5001:8080" # Tilslut din værtsport 5001 til containerport 8080
    networks:
      - loginnetwork
      
networks:
  loginnetwork:
    driver: bridge
    name: auctionnet
